name: CI

on:
  push:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.LOGIN_DOCKER}}
          password: ${{ secrets.PASSWORD_DOCKER}}
      -
        name: Setting up python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12.8"
      -
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      -
        name: Testing the project
        run: |
          coverage run --omit=*/tests.py manage.py test
      -
        name: Test report
        run: coverage report --fail-under=80
      -
        name: Linting with flake8
        run: flake8
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: True
          tags: nvendrisse/oc-lettings-fr:latest
          
