name: CI

on:
  push:
    branches: [ "master" ]

jobs:
  login:
    runs-on: ubuntu-latest
    
    steps:
    -
      name: Login to Docker
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.LOGIN }}
        password: ${{ secrets.TOKEN }}

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
