name: CI

on:
  push:
    branches: [ "master" ]

jobs:
 
  login:
    runs-on: ubuntu-latest
    
    steps:
    -
      name: Login to Docker
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.LOGIN }}
        password: ${{ secrets.TOKEN }}

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
       
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          SENTRY_KEY_URL: ${{ secrets.SENTRY_KEY_URL }}
        run: |
          coverage run -m pytest ./oc_lettings_site
          coverage report
      - name: Run Quality
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          SENTRY_KEY_URL: ${{ secrets.SENTRY_KEY_URL }}
        run: |
          flake8 ./oc_lettings_site
